public:
  seed: 42
  inter.loc: ../data/intermediate/
  data.loc: ../data/
  result.loc: ../result/
  fig.loc: ../figures/
preprocess:
  tag: Preprocessed
  qt: 2
SparseCCA:
  tag: SparseCCA
  num_cores: 12
  num_componets: 10
  FDR.cutoff: 0.1